#!/usr/bin/env python3
"""
Generate Ansible inventory from servers.json with per-server agent tokens.
Usage:
    python3 gen-inventory.py                  # print to stdout
    python3 gen-inventory.py -o inventory     # write to file
    python3 gen-inventory.py --skip-ips 192.168.1.1,192.168.1.2  # exclude IPs
"""
import json
import sys
import argparse
from pathlib import Path

SERVERS_JSON = Path(__file__).parent / "backend" / "servers.json"

# IPs to always skip (gateways, routers, etc.)
DEFAULT_SKIP = {"192.168.1.1", "192.168.1.2", "192.168.1.5"}


def load_servers():
    with open(SERVERS_JSON) as f:
        return json.load(f).get("servers", [])


def is_valid_ip(host):
    parts = host.split(".")
    return len(parts) == 4 and all(p.isdigit() and 0 <= int(p) <= 255 for p in parts)


def main():
    parser = argparse.ArgumentParser(description="Generate Ansible inventory from servers.json")
    parser.add_argument("-o", "--output", help="Output file (default: stdout)")
    parser.add_argument("--skip-ips", help="Comma-separated IPs to skip", default="")
    parser.add_argument("--user", help="SSH user for all hosts", default="administrator")
    parser.add_argument("--backend-host", help="Backend WebSocket host IP", default="")
    args = parser.parse_args()

    skip = DEFAULT_SKIP | {ip.strip() for ip in args.skip_ips.split(",") if ip.strip()}
    servers = load_servers()

    # Try to detect backend host from servers.json if not given
    backend_host = args.backend_host
    if not backend_host:
        for s in servers:
            if "docker-setup" in s.get("name", "").lower() or s.get("host") == "192.168.1.100":
                backend_host = s["host"]
                break
    if not backend_host:
        backend_host = "192.168.1.100"

    ws_url = f"ws://{backend_host}:9090/ws/agent"

    lines = [
        "# Auto-generated by gen-inventory.py — do not edit manually",
        f"# Backend: {ws_url}",
        "",
        "[agents]",
    ]

    count = 0
    for s in servers:
        host = s.get("host", "").strip()
        if not host or host in skip:
            continue
        if not is_valid_ip(host):
            continue

        token = s.get("agent_token", "")
        if not token:
            continue

        name = s.get("name", host).replace(" ", "_")
        lines.append(
            f"{host:<20} ansible_user={args.user} "
            f"agent_token={token} "
            f"# {name}"
        )
        count += 1

    lines += [
        "",
        "[agents:vars]",
        f"serverctl_url={ws_url}",
        f"ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ConnectTimeout=10'",
    ]

    output = "\n".join(lines) + "\n"

    if args.output:
        Path(args.output).write_text(output)
        print(f"[✓] Inventory written to '{args.output}' ({count} servers)")
    else:
        print(output)
        print(f"# Total: {count} servers", file=sys.stderr)


if __name__ == "__main__":
    main()
